version: 1

prompts:
  - |-
    You are a strict UML analysis assistant. Always ground your answers only in the provided UML Diagram. Format lists of classes or methods clearly. Keep your answers short
    Question= {{question}} , UML Diagram= {{uml}}         

providers:
  # Hosted APIs
  - id: google:gemini-2.5-flash-lite
    config:
      apiKey: ${GOOGLE_API_KEY}
  
  - id: google:gemini-2.5-pro
    config:
      apiKey: ${GOOGLE_API_KEY}
 
  #- id: openai:chat:gpt-5
  #  config:
  #    temperature: 0
  #    apiKey: 
  #- id: anthropic:messages:claude-sonnet-4-20250514
  #  config:
  #    temperature: 0
  #    apiKey: 
#PlantUML:
#tests: file://plantUML-tests.yml
#JSON:
tests: file://json-tests.yml